Add Bottom Floating Menu Component
Somehow-I-Code/marquei-web pull request #10
Opened 2024-02-14 00:00 UTC by RafaRafa26

Resultado atual:

![Captura de tela 2024-02-13 205834](https://github.com/goislimat/marquei-web/assets/129136093/cce19334-adc5-4924-aa10-c3195587e059)

2024-02-14 21:19 UTC, goislimat reviewed
Gostaria de ver essas alterações antes de aprovar.

2024-02-14 21:19 UTC, goislimat commented on tailwind.config.ts
> +        customPurple: "#211147",
Pergunta real pra saber sua opinião, o que acha de encontrarmos uma cor parecida já na paleta do tailwind pra evitar de adicionarmos essas cores e depois ter dificuldades pra trabalhar variações dela?

https://tailwindcss.com/docs/customizing-colors

2024-02-14 21:19 UTC, goislimat commented on src/app/components/BottomFloatingMenu.tsx
> +            />
Eu vou te pedir pra que aqui vc só use svg no ícone de `+` o texto eu quero que vc mantenha como texto mesmo. Quanto ao fundo branco e bordas arredondadas, tente chegar nesse resultado usando css.

2024-02-14 21:19 UTC, goislimat commented on src/app/style.css
> -  align-items: center;
Massa demais já estar usando o tailwind! ⭐️

2024-02-15 00:54 UTC, RafaRafa26 commented
> Gostaria de ver essas alterações antes de aprovar.

Subi a foto de novo, acho que bugou quando tentei subir pela primeira vez.

2024-02-15 00:57 UTC, RafaRafa26 commented on tailwind.config.ts
> +        customPurple: "#211147",
Por mim sem problemas, vou procurar alguma parecida e fazer um novo commit.

2024-02-15 01:02 UTC, RafaRafa26 commented on src/app/components/BottomFloatingMenu.tsx
> +            />
Ok

2024-02-16 02:41 UTC, GiAmaral commented on src/app/components/BottomFloatingMenu.tsx
> +const BottomFloatingMenu = () => {
Eu estou usando o export function NomeDoComponente(){....}
Depois poderíamos discutir sobre um padrão para criação dos componentes

2024-02-16 02:44 UTC, GiAmaral commented on tailwind.config.ts
> +      }
Tem alteração no arquivo, mas nenhuma config alterada, é melhor voltar pro que tava antes

2024-02-16 14:12 UTC, RafaRafa26 commented on tailwind.config.ts
> +      }
Eu tinha criado uma cor customizada para usar exatamente a mesma cor do layout que definimos no Figma, mas o Thiago sugeriu usar uma cor que já existe na paleta de cores do Tailwind para ficar mais fácil caso a gente queira usar alguma variação de cor, por isso retirei essas linhas de código.

2024-02-16 14:32 UTC, RafaRafa26 commented on src/app/components/BottomFloatingMenu.tsx
> +const BottomFloatingMenu = () => {
Eu fiz a exportação no final porque acho mais simples para entender o código, mas podemos fazer a exportação direto na função também.

2024-02-18 22:44 UTC, GiAmaral commented on tailwind.config.ts
> +      }
Entendi

2024-02-19 15:48 UTC, goislimat requested changes
Duas pequenas mudanças pra gente poder seguir

2024-02-19 15:48 UTC, goislimat commented on src/app/components/BottomFloatingMenu.tsx
> +const BottomFloatingMenu = () => {
Vamos seguir com o padrão abaixo para criação dos nossos componentes. Vamos resguardar o uso de arrow functions para maps, filters e demais callbacks.

```javascript
export default function ComponentName() { }
```

2024-02-19 15:48 UTC, goislimat commented on tailwind.config.ts
> +      }
Eu vou precisar que vc reverta essas alterações pq esse arquivo não foi mudado. Eu não gostaria de ver um commit nesse arquivo apenas por ter havido adição de uma linha e remoção de uma vírgula.

O comando abaixo vai fazer com que esse arquivo seja substituído pela versão da main (que é a versão original desse arquivo e que não contém essas alterações).

```bash
# abra o terminal na pasta raiz do projeto
git checkout main -- tailwind-config.ts
```

2024-02-19 21:52 UTC, goislimat approved these changes
Agora sim! Vlw pelas alterações.

2024-02-20 00:15 UTC, merged